name: Build and Deploy to Dev

env:
  AZURE_FUNCTIONAPP_NAME: 'drhelius-demo-func'
  POM_XML_DIRECTORY: '.'
  JAVA_VERSION: '11'

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy-to-dev:

    runs-on: windows-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: 'Build Using Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.POM_XML_DIRECTORY }}'
          mvn clean package
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.POM_XML_DIRECTORY }}'
          respect-pom-xml: true
          slot-name: 'dev'

