name: Build and Deploy

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
