name: Swap Dev to Pro

env:
  AZURE_FUNCTIONAPP_NAME: 'demo-func-drhelius'
  RESOURCE_GROUP: 'functions'
  SOURCE_SLOT: 'development'
  TARGET_SLOT: 'production'

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  swap:

    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Swap slots
        uses: azure/CLI@v1
        with:
          inlineScript: |

           az functionapp deployment slot swap \
             -g ${{ env.RESOURCE_GROUP }} \
             -n ${{ env.AZURE_FUNCTIONAPP_NAME }} \
             --slot ${{ env.SOURCE_SLOT }} \
            --target-slot ${{ env.TARGET_SLOT }}          

